jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiry: 600000
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiry: 15552000000
    hash:
      key: ${JWT_REFRESH_HASH_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 5s
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
      client-type: lettuce
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    retry:
      max-attempts: 2
      backoff:
        initial-interval: 2s
        multiplier: 2
        max-interval: 10s
      on-client-errors: false

livo:
  ratelimit:
    enabled: true
    write:
      capacity: 10
      refill-tokens: 10
      refill-duration: 60
    read:
      capacity: 60
      refill-tokens: 60
      refill-duration: 60